app/cf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

urlpatterns = [
    path("", TemplateView.as_view(template_name="index.html"), name="home"),
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("lessons/", include("lessons.urls", namespace="lessons")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/lessons/urls.py
from urllib.parse import urlparse
from django.urls import path

from . import views

app_name = "lessons"


urlpatterns = [
    path("", views.LessonListView.as_view(), name="lesson-list"),
    path("<slug:slug>", views.LessonDetailView.as_view(), name="lesson-detail"),
]

app/lessons/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from django_resized import ResizedImageField
from hitcount.models import HitCountMixin


class PublishedLessonManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status="published")


class Lesson(HitCountMixin, models.Model):
    LESSON_STATUSES = [
        ("draft", "Draft"),
        ("published", "Published"),
    ]
    status = models.CharField(max_length=25, choices=LESSON_STATUSES, default="draft")
    title = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(max_length=255, unique=True, blank=True)
    description = models.TextField(blank=True)
    instructions = models.TextField(blank=True)
    image = ResizedImageField(
        size=[500, 300],
        upload_to="lesson_images",
        blank=True,
        null=True,
        default="img/lesson_default.png",
    )
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = models.Manager()
    published_objects = PublishedLessonManager()

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Lesson, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("lessons:lesson-detail", kwargs={"slug": self.slug})

    def __str__(self):
        return self.title

app/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.text import slugify
# from django.urls import reverse
from django_resized import ResizedImageField


class User(AbstractUser):
    is_learner = models.BooleanField(default=True)


GENDER_LIST = [
    ("M", "M"),
    ("F", "F"),
]


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="profile")
    first_name = models.CharField(max_length=65, blank=True)
    last_name = models.CharField(max_length=65, blank=True)
    slug = models.SlugField(max_length=65, blank=True)
    gender = models.CharField(max_length=1, choices=GENDER_LIST)
    dob = models.DateField(blank=True, null=True)
    bio = models.TextField(blank=True)
    phone = models.CharField(max_length=25, blank=True)
    image = ResizedImageField(size=[500, 300], upload_to='profile_images', blank=True, null=True, default='img/default.png')
    twitter_handle = models.CharField(max_length=25, blank=True)
    facebook_link = models.URLField(blank=True)
    instagram_link = models.URLField(blank=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.user.username)
        super(UserProfile, self).save(*args, **kwargs)

    def __str__(self):
        return str(self.user.username)

app/lessons/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from hitcount.views import HitCountDetailView, HitCountMixin

from .models import Lesson


class LessonListView(HitCountMixin, ListView):
    model = Lesson
    count_hit = True

    def get_queryset(self):
        queryset = Lesson.published_objects.all()
        return queryset


class LessonDetailView(HitCountDetailView):
    model = Lesson
    count_hit = True

app/users/views.py
from django.shortcuts import render

# Create your views here.

app/templates/base.html
{% load static %}

<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport"
        content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link
        href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
        rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
        crossorigin="anonymous">
    <link rel="preconnect"
        href="https://fonts.googleapis.com">
    <link rel="preconnect"
        href="https://fonts.gstatic.com"
        crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap"
        rel="stylesheet">
    <link rel="stylesheet"
        href="{% static './css/main.css' %}">
        <link rel="shortcut icon" href="{% static 'img/logo.jpg' %}" type="image/x-icon">
    <title>

        {% block head_title %}

        {% endblock head_title %}
        Learn Django Saint Lucia
    </title>
</head>

<body class="bg-light">
    {% if user.is_authenticated %}
    {% include 'components/header.html' %}
    {% else %}
    {% include 'components/header_guest.html' %}
    {% endif %}
    <div class="container">

        {% block content %}

        {% endblock content %}
    </div>

    {% include 'components/messages.html' %}
    {% include 'components/footer.html' %}
    

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->

    <script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
</body>

</html>

app/templates/components/footer.html
<div class="container">
    <footer
        class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
        <div class="col-sm d-flex align-items-center">
            <a href="/"
                class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
                <svg class="bi"
                    width="30"
                    height="24">
                    <use xlink:href="#bootstrap" />
                </svg>
            </a>
            <span class="text-muted">&copy;
                <script>
                    var CurrentYear = new Date().getFullYear()
                    document.write(CurrentYear)
                </script> 
                <a class="text-muted text-decoration-none"
                   target="_blank" href="https://ksslu.com/"> kingship
                </a> All rights reserved.
            </span>
        </div>

        <ul class="nav col-sm justify-content-end list-unstyled d-flex">

            <li class="ms-3"><a class="text-dark"
                    href="#">
                    <div class="h4">
                        <i class="bi bi-twitter"></i>
                    </div>
                </a>
            </li>
            <li class="ms-3"><a class="text-dark"
                    href="#">
                    <div class="h4">
                        <i class="bi bi-instagram"></i>
                    </div>
                </a>
            </li>
            <li class="ms-3"><a class="text-dark"
                    href="#">
                    <div class="h4">
                        <i class="bi bi-facebook"></i>
                    </div>
                </a>
            </li>
        </ul>
    </footer>
</div>

app/templates/components/header.html
{% load static %}
<header class="p-3 mb-3 border-bottom shadow">
    <div class="container">
        <div
            class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <a href="/"
                class="d-flex align-items-center mb-2 mb-lg-0 text-dark text-decoration-none">
                <img class="rounded p-0 border border-dark border-2"
                    style="width: 2rem;"
                    src="{% static 'img/logo.jpg' %}"
                    alt="logo">
            </a>

            <ul
                class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0 pl-5">
                <li>
                    <a href="{% url 'lessons:lesson-list' %}"
                        class="nav-link px-2 link-secondary">Lessons</a>
                </li>
                <li>
                    <a href="#"
                        class="nav-link px-2 link-secondary">Discussions</a>
                </li>
                <!-- <li><a href="#"
                        class="nav-link px-2 link-dark">Inventory</a></li>
                <li><a href="#"
                        class="nav-link px-2 link-dark">Customers</a></li>
                <li><a href="#"
                        class="nav-link px-2 link-dark">Products</a></li>
                        -->
            </ul>
            <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3">
                <input type="search"
                    class="form-control"
                    placeholder="Search..."
                    aria-label="Search">
            </form>
            <div class="dropdown text-end">
                <a href="#"
                    class="d-block link-dark text-decoration-none dropdown-toggle"
                    id="dropdownUser1"
                    data-bs-toggle="dropdown"
                    aria-expanded="false">

                    <img {%
                        if
                        request.user.profile.image
                        %}
                        src="{{ request.user.profile.image.url }}"
                        {%
                        else
                        %}
                        src="{% static 'img/default.png' %}"
                        {%
                        endif
                        %}
                        alt="pic"
                        width="32"
                        height="32"
                        class="rounded-circle">
                </a>

                <ul class="dropdown-menu text-small"
                    aria-labelledby="dropdownUser1">

                    <li><a class="dropdown-item"
                            href="#">Profile</a></li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>
                    <li><a class="dropdown-item"
                            href="{% url 'account_logout' %}">Sign out</a></li>

                </ul>
            </div>
        </div>
    </div>
</header>

app/templates/components/header_guest.html
{% load static %}
<header class="p-3 mb-3 border-bottom shadow">
  <div class="container">
    <div
      class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
      <a href="/"
        class="d-flex align-items-center mb-2 mb-lg-0 text-dark text-decoration-none">
        <img class="rounded p-0 border border-dark border-2"
          style="width: 2rem;"
          src="{% static 'img/logo.jpg' %}"
          alt="logo">
      </a>
    </div>
  </div>
</header>

app/templates/components/hero.html
<section id="hero"
    class="container my-5 py-5">
    <div
        class="row p-4 pb-5 pe-lg-0 pt-lg-5 align-items-center rounded-3 border shadow-lg">
        <div class="col-lg-7 col-md-12 p-3 p-lg-5 pt-lg-3">
            <p class="display-4">Learn <a
                    class="text-decoration-none text-dark"
                    href="/">Django</a>, the Web Framework </p>
            <p class="display-4 fw-bold">Saint Lucia</p>
            <p class="lead">Django is a high-level Python web framework that
                encourages rapid development and clean, pragmatic design. Built
                by experienced developers, it takes care of much of the hassle
                of web development, so you can focus on writing your app
                without needing to reinvent the wheel. It’s free and open
                source.</p>

            {% if request.user.is_anonymous %}
            <div id="btn"
                class="d-grid gap-2 d-md-flex justify-content-md-start mb-4 mb-lg-3">
                <a type="button"
                    href="{% url 'account_signup' %}"
                    class="btn btn-outline-dark btn-lg px-4 me-md-2 fw-bold">Register</a>
                <a type="button"
                    href="{% url 'account_login' %}"
                    class="btn btn-dark btn-lg px-4 me-md-2 fw-bold">Login</a>
                <!-- <button type="button"
                    class="btn btn-outline-secondary btn-lg px-4">Default</button> -->
            </div>
            {% endif %}

        </div>
        <div
            class="col-lg-4 col-12 offset-lg-1 p-5 mb-lg-0 mb-5 overflow-hidden shadow-lg">
            <img class="rounded-lg-3"
                src="https://media.geeksforgeeks.org/wp-content/cdn-uploads/20210907183436/Why-Django-Framework-is-Best-For-Web-Development.png"
                alt=""
                width="720">
        </div>
    </div>
</section>

app/templates/components/messages.html
{% if messages %}
{% for message in messages %}
<div class="mx-sm-auto">
    <div class="messages alert alert-info alert-dismissible fade show text-center"
        role="alert">
        <strong>{{message}}</strong>
        <button type="button"
            class="btn-close"
            data-bs-dismiss="alert"
            aria-label="Close"></button>
    </div>
</div>
{% endfor %}
{% endif %}

app/templates/index.html
{% extends 'base.html' %}

{% block head_title %}
Home -
{% endblock head_title %}

{% block content %}
{% include 'components/hero.html' %}

{% endblock content %}

app/templates/lessons/lesson_detail.html
{% extends 'base.html' %}

{% load humanize %}
{% load markdown_tags %}
{% load hitcount_tags %}

{% block head_title %}

{% endblock head_title %}

{% block content %}
<div class="my-5 py-5">
  <div class="py-5">
    <h1>{{object.title}}</h1>
    <hr>
    <p>{{object.description}}</p>
    <div class="my-3 mb-5 text-muted text-start small">
      <span>Updated {{object.updated_at|naturaltime}}</span>
      <p>View{{ hitcount.total_hits|pluralize }} {{ hitcount.total_hits }}</p>
    </div>
    <p>{{object.instructions | markdown | safe}}</p>
  </div>
</div>
{% endblock content %}

app/templates/lessons/lesson_list.html
{% extends 'base.html' %}

{% load humanize %}

{% block head_title %}

{% endblock head_title %}


{% block content %}
<div class="my-5 py-5">
  <p>My name is <a
      class="text-decoration-none text-dark my-name"
      href="https://ksslu.com/"
      target="_blank">Swelan Auguste</a> and I taught myself Django and
    now I want to
    teach you</p>
  <hr>
  <div class="py-5">
    <div class="row row-cols-1 row-cols-md-3 g-4">
      {% for lesson in object_list %}
      <div class="col">
        <a class="text-decoration-none text-dark" href="{{ lesson.get_absolute_url }}">
          <div class="card shadow"
            style="width: 18rem;">
            <img src="{{ lesson.image.url }}"
              class="card-img-top"
              alt="...">
            <div class="card-body">
              <h5 class="card-title fw-bold">{{lesson.title}}</h5>
              <p class="card-text">{{lesson.description}}.</p>
            </div>
            <hr>
            <div class="my-3 px-3">
              <p class="card-text text-muted small text-end">Updated
                {{lesson.updated_at|naturaltime}}</p>
            </div>
          </div>
        </a>
      </div>
      {% empty %}
    </div>
    <h1 class="text-center my-5 py-5">No lessons found.</h1>
    {% endfor %}
  </div>
  {% endblock content %}

app/templates/login_logout.html
{% extends 'base.html' %}
{% include 'account/login.html' %}
{% include 'account/signup.html' %}